use grades_list_tests;
CREATE TABLE TEST SELECT MARKS.ID, STUDENTS.FIRST_NAME, STUDENTS.LAST_NAME, MARKS.MARK, MARKS.DATE_OF_RECEIVING FROM LEARNING_SUBJECTS, MARKS, STUDENTS WHERE LEARNING_SUBJECTS.SUBJECT_ID = 2 AND LEARNING_SUBJECTS.ID = MARKS.LEARNING_SUBJECT_ID AND LEARNING_SUBJECTS.STUDENT_ID = STUDENTS.ID;
SELECT * FROM TEST;