use grades_list_tests;
CREATE TABLE TEST SELECT MARKS.ID, MARKS.MARK, MARKS.DATE_OF_RECEIVING FROM MARKS, LEARNING_SUBJECTS WHERE LEARNING_SUBJECTS.STUDENT_ID = 1 AND LEARNING_SUBJECTS.SUBJECT_ID = 2 AND MARKS.DATE_OF_RECEIVING >= "2017-09-09" AND MARKS.DATE_OF_RECEIVING <= "2019-01-22";
SELECT * FROM TEST;