use grades_list_tests;
CREATE TABLE TEST SELECT SUBJECTS.ID, SUBJECTS.NAME FROM LEARNING_SUBJECTS, SUBJECTS  WHERE LEARNING_SUBJECTS.STUDENT_ID = 1 AND LEARNING_SUBJECTS.SUBJECT_ID = SUBJECTS.ID;
SELECT * FROM TEST;