use grades_list_tests;
CREATE TABLE TEST SELECT MARKS.ID, SUBJECTS.NAME, MARKS.MARK, MARKS.DATE_OF_RECEIVING FROM LEARNING_SUBJECTS, MARKS, SUBJECTS WHERE LEARNING_SUBJECTS.STUDENT_ID = 1 AND LEARNING_SUBJECTS.ID = MARKS.LEARNING_SUBJECT_ID AND LEARNING_SUBJECTS.SUBJECT_ID = SUBJECTS.ID;
SELECT * FROM TEST;